### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by robinsalehjan** [josephyi/viktor#2]
Hi!

Came across your post on the league forums. This implementation is the best one by far.

What's missing:
- Tournament API
- Unit tests
- Anything else?

Should I fork and work on this library? or, help out the developer working on the [velkoz](https://github.com/Tim-Machine/velkoz) library?

**Comment by josephyi** [comment]
Yes, any help would be appreciated! I'm still learning the language, so it'd be great to learn from other contributor's work.

**Comment by josephyi** [comment]
I can either add you as a collaborator, or you can just fork+pull request. Whatever works for you!

**Comment by robinsalehjan** [comment]
You can add me as a collaborator. 

I'm a bit busy in the coming weeks due to exams, but will probably start contributing heavily in the middle of next month.

**Comment by josephyi** [comment]
Great! I'll start doing pull requests for any work I do then. Look forward to working with you!
